
services:
  postgres:
    image: postgres:15
    container_name: visitor-management-db
    ports:
      - '5432:5432'
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgrespw
      POSTGRES_DB: visitor_db
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: always

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: visitor-management-app
    ports:
      - '3000:3000'
    environment:
      - DATABASE_URL=postgresql://postgres:postgrespw@postgres:5432/visitor_db
      - DIRECT_URL=postgresql://postgres:postgrespw@postgres:5432/visitor_db
      - SMS_API_KEY=${SMS_API_KEY}
      - NEXTAUTH_SECRET=${NEXTAUTH_SECRET}
      - NEXTAUTH_URL=http://localhost:3000
    depends_on:
      - postgres
    restart: always

volumes:
  postgres_data:
